// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: cart.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cart message
type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      *Money                 `protobuf:"bytes,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount      *Money                 `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	Total         *Money                 `protobuf:"bytes,6,opt,name=total,proto3" json:"total,omitempty"`
	CouponCode    string                 `protobuf:"bytes,7,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	IsAbandoned   bool                   `protobuf:"varint,8,opt,name=is_abandoned,json=isAbandoned,proto3" json:"is_abandoned,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *Timestamp             `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *Cart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cart) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetSubtotal() *Money {
	if x != nil {
		return x.Subtotal
	}
	return nil
}

func (x *Cart) GetDiscount() *Money {
	if x != nil {
		return x.Discount
	}
	return nil
}

func (x *Cart) GetTotal() *Money {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Cart) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *Cart) GetIsAbandoned() bool {
	if x != nil {
		return x.IsAbandoned
	}
	return false
}

func (x *Cart) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cart) GetUpdatedAt() *Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Cart item message
type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CartId        string                 `protobuf:"bytes,2,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,4,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Sku           string                 `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     *Money                 `protobuf:"bytes,9,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    *Money                 `protobuf:"bytes,10,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartItem) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *CartItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CartItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetUnitPrice() *Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

func (x *CartItem) GetTotalPrice() *Money {
	if x != nil {
		return x.TotalPrice
	}
	return nil
}

// Get cart request
type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Add to cart request
type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     *Money                 `protobuf:"bytes,8,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *AddToCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToCartRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddToCartRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *AddToCartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddToCartRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AddToCartRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *AddToCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddToCartRequest) GetUnitPrice() *Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

type AddToCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartResponse) Reset() {
	*x = AddToCartResponse{}
	mi := &file_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartResponse) ProtoMessage() {}

func (x *AddToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartResponse.ProtoReflect.Descriptor instead.
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{5}
}

func (x *AddToCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Update item quantity request
type UpdateItemQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQuantityRequest) Reset() {
	*x = UpdateItemQuantityRequest{}
	mi := &file_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQuantityRequest) ProtoMessage() {}

func (x *UpdateItemQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemQuantityRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemQuantityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateItemQuantityRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateItemQuantityRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateItemQuantityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQuantityResponse) Reset() {
	*x = UpdateItemQuantityResponse{}
	mi := &file_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQuantityResponse) ProtoMessage() {}

func (x *UpdateItemQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQuantityResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemQuantityResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateItemQuantityResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Remove item request
type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type RemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	mi := &file_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Clear cart request
type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{10}
}

func (x *ClearCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{11}
}

func (x *ClearCartResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Apply coupon request
type ApplyCouponRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode     string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	DiscountAmount *Money                 `protobuf:"bytes,3,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyCouponRequest) Reset() {
	*x = ApplyCouponRequest{}
	mi := &file_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCouponRequest) ProtoMessage() {}

func (x *ApplyCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCouponRequest.ProtoReflect.Descriptor instead.
func (*ApplyCouponRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyCouponRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApplyCouponRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *ApplyCouponRequest) GetDiscountAmount() *Money {
	if x != nil {
		return x.DiscountAmount
	}
	return nil
}

type ApplyCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCouponResponse) Reset() {
	*x = ApplyCouponResponse{}
	mi := &file_cart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCouponResponse) ProtoMessage() {}

func (x *ApplyCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCouponResponse.ProtoReflect.Descriptor instead.
func (*ApplyCouponResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyCouponResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Remove coupon request
type RemoveCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCouponRequest) Reset() {
	*x = RemoveCouponRequest{}
	mi := &file_cart_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCouponRequest) ProtoMessage() {}

func (x *RemoveCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCouponRequest.ProtoReflect.Descriptor instead.
func (*RemoveCouponRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveCouponRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCouponResponse) Reset() {
	*x = RemoveCouponResponse{}
	mi := &file_cart_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCouponResponse) ProtoMessage() {}

func (x *RemoveCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCouponResponse.ProtoReflect.Descriptor instead.
func (*RemoveCouponResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveCouponResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x12\x04cart\x1a\fcommon.proto\"\xf8\x02\n" +
	"\x04Cart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x05items\x18\x03 \x03(\v2\x0e.cart.CartItemR\x05items\x12)\n" +
	"\bsubtotal\x18\x04 \x01(\v2\r.common.MoneyR\bsubtotal\x12)\n" +
	"\bdiscount\x18\x05 \x01(\v2\r.common.MoneyR\bdiscount\x12#\n" +
	"\x05total\x18\x06 \x01(\v2\r.common.MoneyR\x05total\x12\x1f\n" +
	"\vcoupon_code\x18\a \x01(\tR\n" +
	"couponCode\x12!\n" +
	"\fis_abandoned\x18\b \x01(\bR\visAbandoned\x120\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x11.common.TimestampR\tupdatedAt\"\xa7\x02\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acart_id\x18\x02 \x01(\tR\x06cartId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x04 \x01(\tR\tvariantId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x10\n" +
	"\x03sku\x18\a \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x05R\bquantity\x12,\n" +
	"\n" +
	"unit_price\x18\t \x01(\v2\r.common.MoneyR\tunitPrice\x12.\n" +
	"\vtotal_price\x18\n" +
	" \x01(\v2\r.common.MoneyR\n" +
	"totalPrice\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x0fGetCartResponse\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart\"\xef\x01\n" +
	"\x10AddToCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12,\n" +
	"\n" +
	"unit_price\x18\b \x01(\v2\r.common.MoneyR\tunitPrice\"3\n" +
	"\x11AddToCartResponse\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart\"i\n" +
	"\x19UpdateItemQuantityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"<\n" +
	"\x1aUpdateItemQuantityResponse\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart\"E\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"4\n" +
	"\x12RemoveItemResponse\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x11ClearCartResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\"\x86\x01\n" +
	"\x12ApplyCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\x126\n" +
	"\x0fdiscount_amount\x18\x03 \x01(\v2\r.common.MoneyR\x0ediscountAmount\"5\n" +
	"\x13ApplyCouponResponse\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart\".\n" +
	"\x13RemoveCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"6\n" +
	"\x14RemoveCouponResponse\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart2\xe6\x03\n" +
	"\vCartService\x126\n" +
	"\aGetCart\x12\x14.cart.GetCartRequest\x1a\x15.cart.GetCartResponse\x12<\n" +
	"\tAddToCart\x12\x16.cart.AddToCartRequest\x1a\x17.cart.AddToCartResponse\x12W\n" +
	"\x12UpdateItemQuantity\x12\x1f.cart.UpdateItemQuantityRequest\x1a .cart.UpdateItemQuantityResponse\x12?\n" +
	"\n" +
	"RemoveItem\x12\x17.cart.RemoveItemRequest\x1a\x18.cart.RemoveItemResponse\x12<\n" +
	"\tClearCart\x12\x16.cart.ClearCartRequest\x1a\x17.cart.ClearCartResponse\x12B\n" +
	"\vApplyCoupon\x12\x18.cart.ApplyCouponRequest\x1a\x19.cart.ApplyCouponResponse\x12E\n" +
	"\fRemoveCoupon\x12\x19.cart.RemoveCouponRequest\x1a\x1a.cart.RemoveCouponResponseB/Z-github.com/cqchien/ecomerce-rec/backend/protob\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cart_proto_goTypes = []any{
	(*Cart)(nil),                       // 0: cart.Cart
	(*CartItem)(nil),                   // 1: cart.CartItem
	(*GetCartRequest)(nil),             // 2: cart.GetCartRequest
	(*GetCartResponse)(nil),            // 3: cart.GetCartResponse
	(*AddToCartRequest)(nil),           // 4: cart.AddToCartRequest
	(*AddToCartResponse)(nil),          // 5: cart.AddToCartResponse
	(*UpdateItemQuantityRequest)(nil),  // 6: cart.UpdateItemQuantityRequest
	(*UpdateItemQuantityResponse)(nil), // 7: cart.UpdateItemQuantityResponse
	(*RemoveItemRequest)(nil),          // 8: cart.RemoveItemRequest
	(*RemoveItemResponse)(nil),         // 9: cart.RemoveItemResponse
	(*ClearCartRequest)(nil),           // 10: cart.ClearCartRequest
	(*ClearCartResponse)(nil),          // 11: cart.ClearCartResponse
	(*ApplyCouponRequest)(nil),         // 12: cart.ApplyCouponRequest
	(*ApplyCouponResponse)(nil),        // 13: cart.ApplyCouponResponse
	(*RemoveCouponRequest)(nil),        // 14: cart.RemoveCouponRequest
	(*RemoveCouponResponse)(nil),       // 15: cart.RemoveCouponResponse
	(*Money)(nil),                      // 16: common.Money
	(*Timestamp)(nil),                  // 17: common.Timestamp
	(*Response)(nil),                   // 18: common.Response
}
var file_cart_proto_depIdxs = []int32{
	1,  // 0: cart.Cart.items:type_name -> cart.CartItem
	16, // 1: cart.Cart.subtotal:type_name -> common.Money
	16, // 2: cart.Cart.discount:type_name -> common.Money
	16, // 3: cart.Cart.total:type_name -> common.Money
	17, // 4: cart.Cart.created_at:type_name -> common.Timestamp
	17, // 5: cart.Cart.updated_at:type_name -> common.Timestamp
	16, // 6: cart.CartItem.unit_price:type_name -> common.Money
	16, // 7: cart.CartItem.total_price:type_name -> common.Money
	0,  // 8: cart.GetCartResponse.cart:type_name -> cart.Cart
	16, // 9: cart.AddToCartRequest.unit_price:type_name -> common.Money
	0,  // 10: cart.AddToCartResponse.cart:type_name -> cart.Cart
	0,  // 11: cart.UpdateItemQuantityResponse.cart:type_name -> cart.Cart
	0,  // 12: cart.RemoveItemResponse.cart:type_name -> cart.Cart
	18, // 13: cart.ClearCartResponse.response:type_name -> common.Response
	16, // 14: cart.ApplyCouponRequest.discount_amount:type_name -> common.Money
	0,  // 15: cart.ApplyCouponResponse.cart:type_name -> cart.Cart
	0,  // 16: cart.RemoveCouponResponse.cart:type_name -> cart.Cart
	2,  // 17: cart.CartService.GetCart:input_type -> cart.GetCartRequest
	4,  // 18: cart.CartService.AddToCart:input_type -> cart.AddToCartRequest
	6,  // 19: cart.CartService.UpdateItemQuantity:input_type -> cart.UpdateItemQuantityRequest
	8,  // 20: cart.CartService.RemoveItem:input_type -> cart.RemoveItemRequest
	10, // 21: cart.CartService.ClearCart:input_type -> cart.ClearCartRequest
	12, // 22: cart.CartService.ApplyCoupon:input_type -> cart.ApplyCouponRequest
	14, // 23: cart.CartService.RemoveCoupon:input_type -> cart.RemoveCouponRequest
	3,  // 24: cart.CartService.GetCart:output_type -> cart.GetCartResponse
	5,  // 25: cart.CartService.AddToCart:output_type -> cart.AddToCartResponse
	7,  // 26: cart.CartService.UpdateItemQuantity:output_type -> cart.UpdateItemQuantityResponse
	9,  // 27: cart.CartService.RemoveItem:output_type -> cart.RemoveItemResponse
	11, // 28: cart.CartService.ClearCart:output_type -> cart.ClearCartResponse
	13, // 29: cart.CartService.ApplyCoupon:output_type -> cart.ApplyCouponResponse
	15, // 30: cart.CartService.RemoveCoupon:output_type -> cart.RemoveCouponResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
