// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User event types
type EventType int32

const (
	EventType_UNKNOWN           EventType = 0
	EventType_PAGE_VIEW         EventType = 1
	EventType_PRODUCT_VIEW      EventType = 2
	EventType_PRODUCT_CLICK     EventType = 3
	EventType_ADD_TO_CART       EventType = 4
	EventType_REMOVE_FROM_CART  EventType = 5
	EventType_CHECKOUT_START    EventType = 6
	EventType_CHECKOUT_COMPLETE EventType = 7
	EventType_PURCHASE          EventType = 8
	EventType_SEARCH            EventType = 9
	EventType_CATEGORY_VIEW     EventType = 10
	EventType_WISHLIST_ADD      EventType = 11
	EventType_WISHLIST_REMOVE   EventType = 12
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "PAGE_VIEW",
		2:  "PRODUCT_VIEW",
		3:  "PRODUCT_CLICK",
		4:  "ADD_TO_CART",
		5:  "REMOVE_FROM_CART",
		6:  "CHECKOUT_START",
		7:  "CHECKOUT_COMPLETE",
		8:  "PURCHASE",
		9:  "SEARCH",
		10: "CATEGORY_VIEW",
		11: "WISHLIST_ADD",
		12: "WISHLIST_REMOVE",
	}
	EventType_value = map[string]int32{
		"UNKNOWN":           0,
		"PAGE_VIEW":         1,
		"PRODUCT_VIEW":      2,
		"PRODUCT_CLICK":     3,
		"ADD_TO_CART":       4,
		"REMOVE_FROM_CART":  5,
		"CHECKOUT_START":    6,
		"CHECKOUT_COMPLETE": 7,
		"PURCHASE":          8,
		"SEARCH":            9,
		"CATEGORY_VIEW":     10,
		"WISHLIST_ADD":      11,
		"WISHLIST_REMOVE":   12,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

// User event
type UserEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     EventType              `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=event.EventType" json:"event_type,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referrer      string                 `protobuf:"bytes,8,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *UserEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_UNKNOWN
}

func (x *UserEvent) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *UserEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UserEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *UserEvent) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *UserEvent) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Product interaction event
type ProductEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Position      int32                  `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"` // Position in list/carousel
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`      // search, recommendation, category, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductEvent) Reset() {
	*x = ProductEvent{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductEvent) ProtoMessage() {}

func (x *ProductEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductEvent.ProtoReflect.Descriptor instead.
func (*ProductEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *ProductEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductEvent) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ProductEvent) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductEvent) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ProductEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Search event
type SearchEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ResultsCount     int32                  `protobuf:"varint,2,opt,name=results_count,json=resultsCount,proto3" json:"results_count,omitempty"`
	ResultProductIds []string               `protobuf:"bytes,3,rep,name=result_product_ids,json=resultProductIds,proto3" json:"result_product_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchEvent) Reset() {
	*x = SearchEvent{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEvent) ProtoMessage() {}

func (x *SearchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEvent.ProtoReflect.Descriptor instead.
func (*SearchEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *SearchEvent) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchEvent) GetResultsCount() int32 {
	if x != nil {
		return x.ResultsCount
	}
	return 0
}

func (x *SearchEvent) GetResultProductIds() []string {
	if x != nil {
		return x.ResultProductIds
	}
	return nil
}

// Track event request
type TrackEventRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType EventType              `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=event.EventType" json:"event_type,omitempty"`
	// Types that are valid to be assigned to EventData:
	//
	//	*TrackEventRequest_ProductEvent
	//	*TrackEventRequest_SearchEvent
	EventData     isTrackEventRequest_EventData `protobuf_oneof:"event_data"`
	Metadata      map[string]string             `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *TrackEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrackEventRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TrackEventRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_UNKNOWN
}

func (x *TrackEventRequest) GetEventData() isTrackEventRequest_EventData {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *TrackEventRequest) GetProductEvent() *ProductEvent {
	if x != nil {
		if x, ok := x.EventData.(*TrackEventRequest_ProductEvent); ok {
			return x.ProductEvent
		}
	}
	return nil
}

func (x *TrackEventRequest) GetSearchEvent() *SearchEvent {
	if x != nil {
		if x, ok := x.EventData.(*TrackEventRequest_SearchEvent); ok {
			return x.SearchEvent
		}
	}
	return nil
}

func (x *TrackEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isTrackEventRequest_EventData interface {
	isTrackEventRequest_EventData()
}

type TrackEventRequest_ProductEvent struct {
	ProductEvent *ProductEvent `protobuf:"bytes,4,opt,name=product_event,json=productEvent,proto3,oneof"`
}

type TrackEventRequest_SearchEvent struct {
	SearchEvent *SearchEvent `protobuf:"bytes,5,opt,name=search_event,json=searchEvent,proto3,oneof"`
}

func (*TrackEventRequest_ProductEvent) isTrackEventRequest_EventData() {}

func (*TrackEventRequest_SearchEvent) isTrackEventRequest_EventData() {}

type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *TrackEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrackEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Batch track events request
type BatchTrackEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TrackEventRequest   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTrackEventsRequest) Reset() {
	*x = BatchTrackEventsRequest{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTrackEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTrackEventsRequest) ProtoMessage() {}

func (x *BatchTrackEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTrackEventsRequest.ProtoReflect.Descriptor instead.
func (*BatchTrackEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *BatchTrackEventsRequest) GetEvents() []*TrackEventRequest {
	if x != nil {
		return x.Events
	}
	return nil
}

type BatchTrackEventsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,2,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchTrackEventsResponse) Reset() {
	*x = BatchTrackEventsResponse{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTrackEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTrackEventsResponse) ProtoMessage() {}

func (x *BatchTrackEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTrackEventsResponse.ProtoReflect.Descriptor instead.
func (*BatchTrackEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *BatchTrackEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchTrackEventsResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

// Get user events request (Admin/Debug)
type GetUserEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	EventType     EventType              `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=event.EventType" json:"event_type,omitempty"`
	FromTime      *Timestamp             `protobuf:"bytes,4,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        *Timestamp             `protobuf:"bytes,5,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEventsRequest) Reset() {
	*x = GetUserEventsRequest{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEventsRequest) ProtoMessage() {}

func (x *GetUserEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEventsRequest.ProtoReflect.Descriptor instead.
func (*GetUserEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserEventsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetUserEventsRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_UNKNOWN
}

func (x *GetUserEventsRequest) GetFromTime() *Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *GetUserEventsRequest) GetToTime() *Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

type GetUserEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*UserEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEventsResponse) Reset() {
	*x = GetUserEventsResponse{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEventsResponse) ProtoMessage() {}

func (x *GetUserEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEventsResponse.ProtoReflect.Descriptor instead.
func (*GetUserEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserEventsResponse) GetEvents() []*UserEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetUserEventsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05event\x1a\fcommon.proto\"\x90\x03\n" +
	"\tUserEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12/\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x10.event.EventTypeR\teventType\x12@\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2 .event.UserEvent.PropertiesEntryR\n" +
	"properties\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\x12\x1a\n" +
	"\breferrer\x18\b \x01(\tR\breferrer\x12/\n" +
	"\ttimestamp\x18\t \x01(\v2\x11.common.TimestampR\ttimestamp\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\fProductEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"v\n" +
	"\vSearchEvent\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12#\n" +
	"\rresults_count\x18\x02 \x01(\x05R\fresultsCount\x12,\n" +
	"\x12result_product_ids\x18\x03 \x03(\tR\x10resultProductIds\"\x80\x03\n" +
	"\x11TrackEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12/\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x10.event.EventTypeR\teventType\x12:\n" +
	"\rproduct_event\x18\x04 \x01(\v2\x13.event.ProductEventH\x00R\fproductEvent\x127\n" +
	"\fsearch_event\x18\x05 \x01(\v2\x12.event.SearchEventH\x00R\vsearchEvent\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.event.TrackEventRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"event_data\"I\n" +
	"\x12TrackEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"K\n" +
	"\x17BatchTrackEventsRequest\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.event.TrackEventRequestR\x06events\"]\n" +
	"\x18BatchTrackEventsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fprocessed_count\x18\x02 \x01(\x05R\x0eprocessedCount\"\xf7\x01\n" +
	"\x14GetUserEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12/\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x10.event.EventTypeR\teventType\x12.\n" +
	"\tfrom_time\x18\x04 \x01(\v2\x11.common.TimestampR\bfromTime\x12*\n" +
	"\ato_time\x18\x05 \x01(\v2\x11.common.TimestampR\x06toTime\"}\n" +
	"\x15GetUserEventsResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.event.UserEventR\x06events\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination*\xf2\x01\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tPAGE_VIEW\x10\x01\x12\x10\n" +
	"\fPRODUCT_VIEW\x10\x02\x12\x11\n" +
	"\rPRODUCT_CLICK\x10\x03\x12\x0f\n" +
	"\vADD_TO_CART\x10\x04\x12\x14\n" +
	"\x10REMOVE_FROM_CART\x10\x05\x12\x12\n" +
	"\x0eCHECKOUT_START\x10\x06\x12\x15\n" +
	"\x11CHECKOUT_COMPLETE\x10\a\x12\f\n" +
	"\bPURCHASE\x10\b\x12\n" +
	"\n" +
	"\x06SEARCH\x10\t\x12\x11\n" +
	"\rCATEGORY_VIEW\x10\n" +
	"\x12\x10\n" +
	"\fWISHLIST_ADD\x10\v\x12\x13\n" +
	"\x0fWISHLIST_REMOVE\x10\f2\xf2\x01\n" +
	"\fEventService\x12A\n" +
	"\n" +
	"TrackEvent\x12\x18.event.TrackEventRequest\x1a\x19.event.TrackEventResponse\x12S\n" +
	"\x10BatchTrackEvents\x12\x1e.event.BatchTrackEventsRequest\x1a\x1f.event.BatchTrackEventsResponse\x12J\n" +
	"\rGetUserEvents\x12\x1b.event.GetUserEventsRequest\x1a\x1c.event.GetUserEventsResponseB/Z-github.com/cqchien/ecomerce-rec/backend/protob\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_event_proto_goTypes = []any{
	(EventType)(0),                   // 0: event.EventType
	(*UserEvent)(nil),                // 1: event.UserEvent
	(*ProductEvent)(nil),             // 2: event.ProductEvent
	(*SearchEvent)(nil),              // 3: event.SearchEvent
	(*TrackEventRequest)(nil),        // 4: event.TrackEventRequest
	(*TrackEventResponse)(nil),       // 5: event.TrackEventResponse
	(*BatchTrackEventsRequest)(nil),  // 6: event.BatchTrackEventsRequest
	(*BatchTrackEventsResponse)(nil), // 7: event.BatchTrackEventsResponse
	(*GetUserEventsRequest)(nil),     // 8: event.GetUserEventsRequest
	(*GetUserEventsResponse)(nil),    // 9: event.GetUserEventsResponse
	nil,                              // 10: event.UserEvent.PropertiesEntry
	nil,                              // 11: event.TrackEventRequest.MetadataEntry
	(*Timestamp)(nil),                // 12: common.Timestamp
	(*PaginationRequest)(nil),        // 13: common.PaginationRequest
	(*PaginationResponse)(nil),       // 14: common.PaginationResponse
}
var file_event_proto_depIdxs = []int32{
	0,  // 0: event.UserEvent.event_type:type_name -> event.EventType
	10, // 1: event.UserEvent.properties:type_name -> event.UserEvent.PropertiesEntry
	12, // 2: event.UserEvent.timestamp:type_name -> common.Timestamp
	0,  // 3: event.TrackEventRequest.event_type:type_name -> event.EventType
	2,  // 4: event.TrackEventRequest.product_event:type_name -> event.ProductEvent
	3,  // 5: event.TrackEventRequest.search_event:type_name -> event.SearchEvent
	11, // 6: event.TrackEventRequest.metadata:type_name -> event.TrackEventRequest.MetadataEntry
	4,  // 7: event.BatchTrackEventsRequest.events:type_name -> event.TrackEventRequest
	13, // 8: event.GetUserEventsRequest.pagination:type_name -> common.PaginationRequest
	0,  // 9: event.GetUserEventsRequest.event_type:type_name -> event.EventType
	12, // 10: event.GetUserEventsRequest.from_time:type_name -> common.Timestamp
	12, // 11: event.GetUserEventsRequest.to_time:type_name -> common.Timestamp
	1,  // 12: event.GetUserEventsResponse.events:type_name -> event.UserEvent
	14, // 13: event.GetUserEventsResponse.pagination:type_name -> common.PaginationResponse
	4,  // 14: event.EventService.TrackEvent:input_type -> event.TrackEventRequest
	6,  // 15: event.EventService.BatchTrackEvents:input_type -> event.BatchTrackEventsRequest
	8,  // 16: event.EventService.GetUserEvents:input_type -> event.GetUserEventsRequest
	5,  // 17: event.EventService.TrackEvent:output_type -> event.TrackEventResponse
	7,  // 18: event.EventService.BatchTrackEvents:output_type -> event.BatchTrackEventsResponse
	9,  // 19: event.EventService.GetUserEvents:output_type -> event.GetUserEventsResponse
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_common_proto_init()
	file_event_proto_msgTypes[3].OneofWrappers = []any{
		(*TrackEventRequest_ProductEvent)(nil),
		(*TrackEventRequest_SearchEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
