// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: order.proto

package order

import (
	common "github.com/ecommerce/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order status
type OrderStatus int32

const (
	OrderStatus_PENDING         OrderStatus = 0
	OrderStatus_PROCESSING      OrderStatus = 1
	OrderStatus_PAYMENT_PENDING OrderStatus = 2
	OrderStatus_PAYMENT_FAILED  OrderStatus = 3
	OrderStatus_CONFIRMED       OrderStatus = 4
	OrderStatus_PREPARING       OrderStatus = 5
	OrderStatus_SHIPPED         OrderStatus = 6
	OrderStatus_DELIVERED       OrderStatus = 7
	OrderStatus_CANCELLED       OrderStatus = 8
	OrderStatus_REFUNDED        OrderStatus = 9
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "PROCESSING",
		2: "PAYMENT_PENDING",
		3: "PAYMENT_FAILED",
		4: "CONFIRMED",
		5: "PREPARING",
		6: "SHIPPED",
		7: "DELIVERED",
		8: "CANCELLED",
		9: "REFUNDED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":         0,
		"PROCESSING":      1,
		"PAYMENT_PENDING": 2,
		"PAYMENT_FAILED":  3,
		"CONFIRMED":       4,
		"PREPARING":       5,
		"SHIPPED":         6,
		"DELIVERED":       7,
		"CANCELLED":       8,
		"REFUNDED":        9,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

// Order message
type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal        *common.Money          `protobuf:"bytes,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Shipping        *common.Money          `protobuf:"bytes,5,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Tax             *common.Money          `protobuf:"bytes,6,opt,name=tax,proto3" json:"tax,omitempty"`
	Discount        *common.Money          `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Total           *common.Money          `protobuf:"bytes,8,opt,name=total,proto3" json:"total,omitempty"`
	Status          OrderStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	ShippingAddress *common.Address        `protobuf:"bytes,10,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	BillingAddress  *common.Address        `protobuf:"bytes,11,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,12,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentId       string                 `protobuf:"bytes,13,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Tracking        *TrackingInfo          `protobuf:"bytes,14,opt,name=tracking,proto3" json:"tracking,omitempty"`
	CreatedAt       *common.Timestamp      `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *common.Timestamp      `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetSubtotal() *common.Money {
	if x != nil {
		return x.Subtotal
	}
	return nil
}

func (x *Order) GetShipping() *common.Money {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *Order) GetTax() *common.Money {
	if x != nil {
		return x.Tax
	}
	return nil
}

func (x *Order) GetDiscount() *common.Money {
	if x != nil {
		return x.Discount
	}
	return nil
}

func (x *Order) GetTotal() *common.Money {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *Order) GetShippingAddress() *common.Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *Order) GetBillingAddress() *common.Address {
	if x != nil {
		return x.BillingAddress
	}
	return nil
}

func (x *Order) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Order) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Order) GetTracking() *TrackingInfo {
	if x != nil {
		return x.Tracking
	}
	return nil
}

func (x *Order) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Order item
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     *common.Money          `protobuf:"bytes,8,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    *common.Money          `protobuf:"bytes,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *OrderItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() *common.Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

func (x *OrderItem) GetTotalPrice() *common.Money {
	if x != nil {
		return x.TotalPrice
	}
	return nil
}

// Tracking information
type TrackingInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber    string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier           string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Url               string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ShippedAt         *common.Timestamp      `protobuf:"bytes,4,opt,name=shipped_at,json=shippedAt,proto3" json:"shipped_at,omitempty"`
	EstimatedDelivery *common.Timestamp      `protobuf:"bytes,5,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrackingInfo) Reset() {
	*x = TrackingInfo{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingInfo) ProtoMessage() {}

func (x *TrackingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingInfo.ProtoReflect.Descriptor instead.
func (*TrackingInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *TrackingInfo) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *TrackingInfo) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *TrackingInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TrackingInfo) GetShippedAt() *common.Timestamp {
	if x != nil {
		return x.ShippedAt
	}
	return nil
}

func (x *TrackingInfo) GetEstimatedDelivery() *common.Timestamp {
	if x != nil {
		return x.EstimatedDelivery
	}
	return nil
}

// Create order request
type CreateOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items             []*OrderItemRequest    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ShippingAddressId string                 `protobuf:"bytes,3,opt,name=shipping_address_id,json=shippingAddressId,proto3" json:"shipping_address_id,omitempty"`
	BillingAddressId  string                 `protobuf:"bytes,4,opt,name=billing_address_id,json=billingAddressId,proto3" json:"billing_address_id,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CouponCode        string                 `protobuf:"bytes,6,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetShippingAddressId() string {
	if x != nil {
		return x.ShippingAddressId
	}
	return ""
}

func (x *CreateOrderRequest) GetBillingAddressId() string {
	if x != nil {
		return x.BillingAddressId
	}
	return ""
}

func (x *CreateOrderRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateOrderRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type OrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemRequest) Reset() {
	*x = OrderItemRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemRequest) ProtoMessage() {}

func (x *OrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemRequest.ProtoReflect.Descriptor instead.
func (*OrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *OrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Order           *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PaymentIntentId string                 `protobuf:"bytes,2,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

// Get order request
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// List orders request
type ListOrdersRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filters       *OrderFilters             `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrdersRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOrdersRequest) GetFilters() *OrderFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type OrderFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	FromDate      *common.Timestamp      `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *common.Timestamp      `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFilters) Reset() {
	*x = OrderFilters{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilters) ProtoMessage() {}

func (x *OrderFilters) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilters.ProtoReflect.Descriptor instead.
func (*OrderFilters) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderFilters) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *OrderFilters) GetFromDate() *common.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *OrderFilters) GetToDate() *common.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Orders        []*Order                   `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Cancel order request
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Update order status request
type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Tracking      *TrackingInfo          `protobuf:"bytes,4,opt,name=tracking,proto3" json:"tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOrderStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *UpdateOrderStatusRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetTracking() *TrackingInfo {
	if x != nil {
		return x.Tracking
	}
	return nil
}

type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateOrderStatusResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Get order status history
type GetOrderStatusHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusHistoryRequest) Reset() {
	*x = GetOrderStatusHistoryRequest{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusHistoryRequest) ProtoMessage() {}

func (x *GetOrderStatusHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusHistoryRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderStatusHistoryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderStatusHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*OrderStatusHistory  `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusHistoryResponse) Reset() {
	*x = GetOrderStatusHistoryResponse{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusHistoryResponse) ProtoMessage() {}

func (x *GetOrderStatusHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusHistoryResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderStatusHistoryResponse) GetHistory() []*OrderStatusHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type OrderStatusHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	Timestamp     *common.Timestamp      `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusHistory) Reset() {
	*x = OrderStatusHistory{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusHistory) ProtoMessage() {}

func (x *OrderStatusHistory) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusHistory.ProtoReflect.Descriptor instead.
func (*OrderStatusHistory) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *OrderStatusHistory) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *OrderStatusHistory) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *OrderStatusHistory) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OrderStatusHistory) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\x1a\fcommon.proto\"\x9c\x05\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.order.OrderItemR\x05items\x12)\n" +
	"\bsubtotal\x18\x04 \x01(\v2\r.common.MoneyR\bsubtotal\x12)\n" +
	"\bshipping\x18\x05 \x01(\v2\r.common.MoneyR\bshipping\x12\x1f\n" +
	"\x03tax\x18\x06 \x01(\v2\r.common.MoneyR\x03tax\x12)\n" +
	"\bdiscount\x18\a \x01(\v2\r.common.MoneyR\bdiscount\x12#\n" +
	"\x05total\x18\b \x01(\v2\r.common.MoneyR\x05total\x12*\n" +
	"\x06status\x18\t \x01(\x0e2\x12.order.OrderStatusR\x06status\x12:\n" +
	"\x10shipping_address\x18\n" +
	" \x01(\v2\x0f.common.AddressR\x0fshippingAddress\x128\n" +
	"\x0fbilling_address\x18\v \x01(\v2\x0f.common.AddressR\x0ebillingAddress\x12%\n" +
	"\x0epayment_method\x18\f \x01(\tR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"payment_id\x18\r \x01(\tR\tpaymentId\x12/\n" +
	"\btracking\x18\x0e \x01(\v2\x13.order.TrackingInfoR\btracking\x120\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x11.common.TimestampR\tupdatedAt\"\x8f\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12,\n" +
	"\n" +
	"unit_price\x18\b \x01(\v2\r.common.MoneyR\tunitPrice\x12.\n" +
	"\vtotal_price\x18\t \x01(\v2\r.common.MoneyR\n" +
	"totalPrice\"\xd7\x01\n" +
	"\fTrackingInfo\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x120\n" +
	"\n" +
	"shipped_at\x18\x04 \x01(\v2\x11.common.TimestampR\tshippedAt\x12@\n" +
	"\x12estimated_delivery\x18\x05 \x01(\v2\x11.common.TimestampR\x11estimatedDelivery\"\x82\x02\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.order.OrderItemRequestR\x05items\x12.\n" +
	"\x13shipping_address_id\x18\x03 \x01(\tR\x11shippingAddressId\x12,\n" +
	"\x12billing_address_id\x18\x04 \x01(\tR\x10billingAddressId\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vcoupon_code\x18\x06 \x01(\tR\n" +
	"couponCode\"l\n" +
	"\x10OrderItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"e\n" +
	"\x13CreateOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\x12*\n" +
	"\x11payment_intent_id\x18\x02 \x01(\tR\x0fpaymentIntentId\":\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x10GetOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"\x96\x01\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12-\n" +
	"\afilters\x18\x03 \x01(\v2\x13.order.OrderFiltersR\afilters\"\x96\x01\n" +
	"\fOrderFilters\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12.\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x11.common.TimestampR\bfromDate\x12*\n" +
	"\ato_date\x18\x03 \x01(\v2\x11.common.TimestampR\x06toDate\"v\n" +
	"\x12ListOrdersResponse\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"U\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"S\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\x05order\x18\x02 \x01(\v2\f.order.OrderR\x05order\"\x9b\x01\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12/\n" +
	"\btracking\x18\x04 \x01(\v2\x13.order.TrackingInfoR\btracking\"?\n" +
	"\x19UpdateOrderStatusResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"9\n" +
	"\x1cGetOrderStatusHistoryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"T\n" +
	"\x1dGetOrderStatusHistoryResponse\x123\n" +
	"\ahistory\x18\x01 \x03(\v2\x19.order.OrderStatusHistoryR\ahistory\"\xa4\x01\n" +
	"\x12OrderStatusHistory\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\x12/\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x11.common.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy*\xaa\x01\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\x13\n" +
	"\x0fPAYMENT_PENDING\x10\x02\x12\x12\n" +
	"\x0ePAYMENT_FAILED\x10\x03\x12\r\n" +
	"\tCONFIRMED\x10\x04\x12\r\n" +
	"\tPREPARING\x10\x05\x12\v\n" +
	"\aSHIPPED\x10\x06\x12\r\n" +
	"\tDELIVERED\x10\a\x12\r\n" +
	"\tCANCELLED\x10\b\x12\f\n" +
	"\bREFUNDED\x10\t2\xd6\x03\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12;\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponse\x12A\n" +
	"\n" +
	"ListOrders\x12\x18.order.ListOrdersRequest\x1a\x19.order.ListOrdersResponse\x12D\n" +
	"\vCancelOrder\x12\x19.order.CancelOrderRequest\x1a\x1a.order.CancelOrderResponse\x12V\n" +
	"\x11UpdateOrderStatus\x12\x1f.order.UpdateOrderStatusRequest\x1a .order.UpdateOrderStatusResponse\x12b\n" +
	"\x15GetOrderStatusHistory\x12#.order.GetOrderStatusHistoryRequest\x1a$.order.GetOrderStatusHistoryResponseB\"Z github.com/ecommerce/proto/orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_order_proto_goTypes = []any{
	(OrderStatus)(0),                      // 0: order.OrderStatus
	(*Order)(nil),                         // 1: order.Order
	(*OrderItem)(nil),                     // 2: order.OrderItem
	(*TrackingInfo)(nil),                  // 3: order.TrackingInfo
	(*CreateOrderRequest)(nil),            // 4: order.CreateOrderRequest
	(*OrderItemRequest)(nil),              // 5: order.OrderItemRequest
	(*CreateOrderResponse)(nil),           // 6: order.CreateOrderResponse
	(*GetOrderRequest)(nil),               // 7: order.GetOrderRequest
	(*GetOrderResponse)(nil),              // 8: order.GetOrderResponse
	(*ListOrdersRequest)(nil),             // 9: order.ListOrdersRequest
	(*OrderFilters)(nil),                  // 10: order.OrderFilters
	(*ListOrdersResponse)(nil),            // 11: order.ListOrdersResponse
	(*CancelOrderRequest)(nil),            // 12: order.CancelOrderRequest
	(*CancelOrderResponse)(nil),           // 13: order.CancelOrderResponse
	(*UpdateOrderStatusRequest)(nil),      // 14: order.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil),     // 15: order.UpdateOrderStatusResponse
	(*GetOrderStatusHistoryRequest)(nil),  // 16: order.GetOrderStatusHistoryRequest
	(*GetOrderStatusHistoryResponse)(nil), // 17: order.GetOrderStatusHistoryResponse
	(*OrderStatusHistory)(nil),            // 18: order.OrderStatusHistory
	(*common.Money)(nil),                  // 19: common.Money
	(*common.Address)(nil),                // 20: common.Address
	(*common.Timestamp)(nil),              // 21: common.Timestamp
	(*common.PaginationRequest)(nil),      // 22: common.PaginationRequest
	(*common.PaginationResponse)(nil),     // 23: common.PaginationResponse
}
var file_order_proto_depIdxs = []int32{
	2,  // 0: order.Order.items:type_name -> order.OrderItem
	19, // 1: order.Order.subtotal:type_name -> common.Money
	19, // 2: order.Order.shipping:type_name -> common.Money
	19, // 3: order.Order.tax:type_name -> common.Money
	19, // 4: order.Order.discount:type_name -> common.Money
	19, // 5: order.Order.total:type_name -> common.Money
	0,  // 6: order.Order.status:type_name -> order.OrderStatus
	20, // 7: order.Order.shipping_address:type_name -> common.Address
	20, // 8: order.Order.billing_address:type_name -> common.Address
	3,  // 9: order.Order.tracking:type_name -> order.TrackingInfo
	21, // 10: order.Order.created_at:type_name -> common.Timestamp
	21, // 11: order.Order.updated_at:type_name -> common.Timestamp
	19, // 12: order.OrderItem.unit_price:type_name -> common.Money
	19, // 13: order.OrderItem.total_price:type_name -> common.Money
	21, // 14: order.TrackingInfo.shipped_at:type_name -> common.Timestamp
	21, // 15: order.TrackingInfo.estimated_delivery:type_name -> common.Timestamp
	5,  // 16: order.CreateOrderRequest.items:type_name -> order.OrderItemRequest
	1,  // 17: order.CreateOrderResponse.order:type_name -> order.Order
	1,  // 18: order.GetOrderResponse.order:type_name -> order.Order
	22, // 19: order.ListOrdersRequest.pagination:type_name -> common.PaginationRequest
	10, // 20: order.ListOrdersRequest.filters:type_name -> order.OrderFilters
	0,  // 21: order.OrderFilters.status:type_name -> order.OrderStatus
	21, // 22: order.OrderFilters.from_date:type_name -> common.Timestamp
	21, // 23: order.OrderFilters.to_date:type_name -> common.Timestamp
	1,  // 24: order.ListOrdersResponse.orders:type_name -> order.Order
	23, // 25: order.ListOrdersResponse.pagination:type_name -> common.PaginationResponse
	1,  // 26: order.CancelOrderResponse.order:type_name -> order.Order
	0,  // 27: order.UpdateOrderStatusRequest.status:type_name -> order.OrderStatus
	3,  // 28: order.UpdateOrderStatusRequest.tracking:type_name -> order.TrackingInfo
	1,  // 29: order.UpdateOrderStatusResponse.order:type_name -> order.Order
	18, // 30: order.GetOrderStatusHistoryResponse.history:type_name -> order.OrderStatusHistory
	0,  // 31: order.OrderStatusHistory.status:type_name -> order.OrderStatus
	21, // 32: order.OrderStatusHistory.timestamp:type_name -> common.Timestamp
	4,  // 33: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	7,  // 34: order.OrderService.GetOrder:input_type -> order.GetOrderRequest
	9,  // 35: order.OrderService.ListOrders:input_type -> order.ListOrdersRequest
	12, // 36: order.OrderService.CancelOrder:input_type -> order.CancelOrderRequest
	14, // 37: order.OrderService.UpdateOrderStatus:input_type -> order.UpdateOrderStatusRequest
	16, // 38: order.OrderService.GetOrderStatusHistory:input_type -> order.GetOrderStatusHistoryRequest
	6,  // 39: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	8,  // 40: order.OrderService.GetOrder:output_type -> order.GetOrderResponse
	11, // 41: order.OrderService.ListOrders:output_type -> order.ListOrdersResponse
	13, // 42: order.OrderService.CancelOrder:output_type -> order.CancelOrderResponse
	15, // 43: order.OrderService.UpdateOrderStatus:output_type -> order.UpdateOrderStatusResponse
	17, // 44: order.OrderService.GetOrderStatusHistory:output_type -> order.GetOrderStatusHistoryResponse
	39, // [39:45] is the sub-list for method output_type
	33, // [33:39] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
