// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PENDING    PaymentStatus = 0
	PaymentStatus_PROCESSING PaymentStatus = 1
	PaymentStatus_SUCCEEDED  PaymentStatus = 2
	PaymentStatus_FAILED     PaymentStatus = 3
	PaymentStatus_CANCELLED  PaymentStatus = 4
	PaymentStatus_REFUNDED   PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PENDING",
		1: "PROCESSING",
		2: "SUCCEEDED",
		3: "FAILED",
		4: "CANCELLED",
		5: "REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PENDING":    0,
		"PROCESSING": 1,
		"SUCCEEDED":  2,
		"FAILED":     3,
		"CANCELLED":  4,
		"REFUNDED":   5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

// Payment method type
type PaymentMethodType int32

const (
	PaymentMethodType_CREDIT_CARD      PaymentMethodType = 0
	PaymentMethodType_DEBIT_CARD       PaymentMethodType = 1
	PaymentMethodType_PAYPAL           PaymentMethodType = 2
	PaymentMethodType_BANK_TRANSFER    PaymentMethodType = 3
	PaymentMethodType_CASH_ON_DELIVERY PaymentMethodType = 4
)

// Enum value maps for PaymentMethodType.
var (
	PaymentMethodType_name = map[int32]string{
		0: "CREDIT_CARD",
		1: "DEBIT_CARD",
		2: "PAYPAL",
		3: "BANK_TRANSFER",
		4: "CASH_ON_DELIVERY",
	}
	PaymentMethodType_value = map[string]int32{
		"CREDIT_CARD":      0,
		"DEBIT_CARD":       1,
		"PAYPAL":           2,
		"BANK_TRANSFER":    3,
		"CASH_ON_DELIVERY": 4,
	}
)

func (x PaymentMethodType) Enum() *PaymentMethodType {
	p := new(PaymentMethodType)
	*p = x
	return p
}

func (x PaymentMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethodType) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x PaymentMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodType.Descriptor instead.
func (PaymentMethodType) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

// Payment message
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	Method        PaymentMethodType      `protobuf:"varint,6,opt,name=method,proto3,enum=payment.PaymentMethodType" json:"method,omitempty"`
	TransactionId string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *Timestamp             `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

func (x *Payment) GetMethod() PaymentMethodType {
	if x != nil {
		return x.Method
	}
	return PaymentMethodType_CREDIT_CARD
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Payment) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Payment method
type PaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          PaymentMethodType      `protobuf:"varint,3,opt,name=type,proto3,enum=payment.PaymentMethodType" json:"type,omitempty"`
	Last4         string                 `protobuf:"bytes,4,opt,name=last4,proto3" json:"last4,omitempty"` // Last 4 digits of card
	Brand         string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"` // Visa, Mastercard, etc.
	ExpMonth      int32                  `protobuf:"varint,6,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       int32                  `protobuf:"varint,7,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	IsDefault     bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethod) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentMethod) GetType() PaymentMethodType {
	if x != nil {
		return x.Type
	}
	return PaymentMethodType_CREDIT_CARD
}

func (x *PaymentMethod) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *PaymentMethod) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *PaymentMethod) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *PaymentMethod) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *PaymentMethod) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *PaymentMethod) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Create payment intent request
type CreatePaymentIntentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount          *Money                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Method          PaymentMethodType      `protobuf:"varint,4,opt,name=method,proto3,enum=payment.PaymentMethodType" json:"method,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,5,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentIntentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePaymentIntentRequest) GetMethod() PaymentMethodType {
	if x != nil {
		return x.Method
	}
	return PaymentMethodType_CREDIT_CARD
}

func (x *CreatePaymentIntentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreatePaymentIntentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ClientSecret    string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Status          PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentIntentResponse) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

// Confirm payment request
type ConfirmPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmPaymentRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

type ConfirmPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResponse) Reset() {
	*x = ConfirmPaymentResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResponse) ProtoMessage() {}

func (x *ConfirmPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Cancel payment request
type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *CancelPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CancelPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentResponse) Reset() {
	*x = CancelPaymentResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentResponse) ProtoMessage() {}

func (x *CancelPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *CancelPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Refund payment request
type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // Partial or full refund
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *RefundPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundPaymentRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	RefundId      string                 `protobuf:"bytes,2,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentResponse) Reset() {
	*x = RefundPaymentResponse{}
	mi := &file_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentResponse) ProtoMessage() {}

func (x *RefundPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentResponse.ProtoReflect.Descriptor instead.
func (*RefundPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *RefundPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *RefundPaymentResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

// Get payment status request
type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetPaymentStatusResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Get payment methods request
type GetPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodsRequest) Reset() {
	*x = GetPaymentMethodsRequest{}
	mi := &file_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodsRequest) ProtoMessage() {}

func (x *GetPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaymentMethodsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPaymentMethodsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethods []*PaymentMethod       `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentMethodsResponse) Reset() {
	*x = GetPaymentMethodsResponse{}
	mi := &file_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodsResponse) ProtoMessage() {}

func (x *GetPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{13}
}

func (x *GetPaymentMethodsResponse) GetPaymentMethods() []*PaymentMethod {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

// Add payment method request
type AddPaymentMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          PaymentMethodType      `protobuf:"varint,2,opt,name=type,proto3,enum=payment.PaymentMethodType" json:"type,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Tokenized payment info
	SetAsDefault  bool                   `protobuf:"varint,4,opt,name=set_as_default,json=setAsDefault,proto3" json:"set_as_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentMethodRequest) Reset() {
	*x = AddPaymentMethodRequest{}
	mi := &file_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentMethodRequest) ProtoMessage() {}

func (x *AddPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*AddPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{14}
}

func (x *AddPaymentMethodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetType() PaymentMethodType {
	if x != nil {
		return x.Type
	}
	return PaymentMethodType_CREDIT_CARD
}

func (x *AddPaymentMethodRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetSetAsDefault() bool {
	if x != nil {
		return x.SetAsDefault
	}
	return false
}

type AddPaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentMethodResponse) Reset() {
	*x = AddPaymentMethodResponse{}
	mi := &file_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentMethodResponse) ProtoMessage() {}

func (x *AddPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*AddPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{15}
}

func (x *AddPaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

// Remove payment method request
type RemovePaymentMethodRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemovePaymentMethodRequest) Reset() {
	*x = RemovePaymentMethodRequest{}
	mi := &file_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePaymentMethodRequest) ProtoMessage() {}

func (x *RemovePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*RemovePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{16}
}

func (x *RemovePaymentMethodRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *RemovePaymentMethodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemovePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePaymentMethodResponse) Reset() {
	*x = RemovePaymentMethodResponse{}
	mi := &file_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePaymentMethodResponse) ProtoMessage() {}

func (x *RemovePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*RemovePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{17}
}

func (x *RemovePaymentMethodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\x1a\fcommon.proto\"\x88\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.common.MoneyR\x06amount\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x122\n" +
	"\x06method\x18\x06 \x01(\x0e2\x1a.payment.PaymentMethodTypeR\x06method\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x120\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x11.common.TimestampR\tupdatedAt\"\x9d\x02\n" +
	"\rPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.payment.PaymentMethodTypeR\x04type\x12\x14\n" +
	"\x05last4\x18\x04 \x01(\tR\x05last4\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x1b\n" +
	"\texp_month\x18\x06 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\a \x01(\x05R\aexpYear\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\x120\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x11.common.TimestampR\tcreatedAt\"\xe3\x02\n" +
	"\x1aCreatePaymentIntentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x06amount\x18\x03 \x01(\v2\r.common.MoneyR\x06amount\x122\n" +
	"\x06method\x18\x04 \x01(\x0e2\x1a.payment.PaymentMethodTypeR\x06method\x12*\n" +
	"\x11payment_method_id\x18\x05 \x01(\tR\x0fpaymentMethodId\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.payment.CreatePaymentIntentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x1bCreatePaymentIntentResponse\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\"o\n" +
	"\x15ConfirmPaymentRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\"D\n" +
	"\x16ConfirmPaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\"M\n" +
	"\x14CancelPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"C\n" +
	"\x15CancelPaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\"t\n" +
	"\x14RefundPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12%\n" +
	"\x06amount\x18\x02 \x01(\v2\r.common.MoneyR\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"`\n" +
	"\x15RefundPaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\x12\x1b\n" +
	"\trefund_id\x18\x02 \x01(\tR\brefundId\"8\n" +
	"\x17GetPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"F\n" +
	"\x18GetPaymentStatusResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\"3\n" +
	"\x18GetPaymentMethodsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\\\n" +
	"\x19GetPaymentMethodsResponse\x12?\n" +
	"\x0fpayment_methods\x18\x01 \x03(\v2\x16.payment.PaymentMethodR\x0epaymentMethods\"\x9e\x01\n" +
	"\x17AddPaymentMethodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.payment.PaymentMethodTypeR\x04type\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12$\n" +
	"\x0eset_as_default\x18\x04 \x01(\bR\fsetAsDefault\"Y\n" +
	"\x18AddPaymentMethodResponse\x12=\n" +
	"\x0epayment_method\x18\x01 \x01(\v2\x16.payment.PaymentMethodR\rpaymentMethod\"a\n" +
	"\x1aRemovePaymentMethodRequest\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"7\n" +
	"\x1bRemovePaymentMethodResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*d\n" +
	"\rPaymentStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tSUCCEEDED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\f\n" +
	"\bREFUNDED\x10\x05*i\n" +
	"\x11PaymentMethodType\x12\x0f\n" +
	"\vCREDIT_CARD\x10\x00\x12\x0e\n" +
	"\n" +
	"DEBIT_CARD\x10\x01\x12\n" +
	"\n" +
	"\x06PAYPAL\x10\x02\x12\x11\n" +
	"\rBANK_TRANSFER\x10\x03\x12\x14\n" +
	"\x10CASH_ON_DELIVERY\x10\x042\xd5\x05\n" +
	"\x0ePaymentService\x12`\n" +
	"\x13CreatePaymentIntent\x12#.payment.CreatePaymentIntentRequest\x1a$.payment.CreatePaymentIntentResponse\x12Q\n" +
	"\x0eConfirmPayment\x12\x1e.payment.ConfirmPaymentRequest\x1a\x1f.payment.ConfirmPaymentResponse\x12N\n" +
	"\rCancelPayment\x12\x1d.payment.CancelPaymentRequest\x1a\x1e.payment.CancelPaymentResponse\x12N\n" +
	"\rRefundPayment\x12\x1d.payment.RefundPaymentRequest\x1a\x1e.payment.RefundPaymentResponse\x12W\n" +
	"\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a!.payment.GetPaymentStatusResponse\x12Z\n" +
	"\x11GetPaymentMethods\x12!.payment.GetPaymentMethodsRequest\x1a\".payment.GetPaymentMethodsResponse\x12W\n" +
	"\x10AddPaymentMethod\x12 .payment.AddPaymentMethodRequest\x1a!.payment.AddPaymentMethodResponse\x12`\n" +
	"\x13RemovePaymentMethod\x12#.payment.RemovePaymentMethodRequest\x1a$.payment.RemovePaymentMethodResponseB/Z-github.com/cqchien/ecomerce-rec/backend/protob\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_payment_proto_goTypes = []any{
	(PaymentStatus)(0),                  // 0: payment.PaymentStatus
	(PaymentMethodType)(0),              // 1: payment.PaymentMethodType
	(*Payment)(nil),                     // 2: payment.Payment
	(*PaymentMethod)(nil),               // 3: payment.PaymentMethod
	(*CreatePaymentIntentRequest)(nil),  // 4: payment.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil), // 5: payment.CreatePaymentIntentResponse
	(*ConfirmPaymentRequest)(nil),       // 6: payment.ConfirmPaymentRequest
	(*ConfirmPaymentResponse)(nil),      // 7: payment.ConfirmPaymentResponse
	(*CancelPaymentRequest)(nil),        // 8: payment.CancelPaymentRequest
	(*CancelPaymentResponse)(nil),       // 9: payment.CancelPaymentResponse
	(*RefundPaymentRequest)(nil),        // 10: payment.RefundPaymentRequest
	(*RefundPaymentResponse)(nil),       // 11: payment.RefundPaymentResponse
	(*GetPaymentStatusRequest)(nil),     // 12: payment.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil),    // 13: payment.GetPaymentStatusResponse
	(*GetPaymentMethodsRequest)(nil),    // 14: payment.GetPaymentMethodsRequest
	(*GetPaymentMethodsResponse)(nil),   // 15: payment.GetPaymentMethodsResponse
	(*AddPaymentMethodRequest)(nil),     // 16: payment.AddPaymentMethodRequest
	(*AddPaymentMethodResponse)(nil),    // 17: payment.AddPaymentMethodResponse
	(*RemovePaymentMethodRequest)(nil),  // 18: payment.RemovePaymentMethodRequest
	(*RemovePaymentMethodResponse)(nil), // 19: payment.RemovePaymentMethodResponse
	nil,                                 // 20: payment.CreatePaymentIntentRequest.MetadataEntry
	(*Money)(nil),                       // 21: common.Money
	(*Timestamp)(nil),                   // 22: common.Timestamp
}
var file_payment_proto_depIdxs = []int32{
	21, // 0: payment.Payment.amount:type_name -> common.Money
	0,  // 1: payment.Payment.status:type_name -> payment.PaymentStatus
	1,  // 2: payment.Payment.method:type_name -> payment.PaymentMethodType
	22, // 3: payment.Payment.created_at:type_name -> common.Timestamp
	22, // 4: payment.Payment.updated_at:type_name -> common.Timestamp
	1,  // 5: payment.PaymentMethod.type:type_name -> payment.PaymentMethodType
	22, // 6: payment.PaymentMethod.created_at:type_name -> common.Timestamp
	21, // 7: payment.CreatePaymentIntentRequest.amount:type_name -> common.Money
	1,  // 8: payment.CreatePaymentIntentRequest.method:type_name -> payment.PaymentMethodType
	20, // 9: payment.CreatePaymentIntentRequest.metadata:type_name -> payment.CreatePaymentIntentRequest.MetadataEntry
	0,  // 10: payment.CreatePaymentIntentResponse.status:type_name -> payment.PaymentStatus
	2,  // 11: payment.ConfirmPaymentResponse.payment:type_name -> payment.Payment
	2,  // 12: payment.CancelPaymentResponse.payment:type_name -> payment.Payment
	21, // 13: payment.RefundPaymentRequest.amount:type_name -> common.Money
	2,  // 14: payment.RefundPaymentResponse.payment:type_name -> payment.Payment
	2,  // 15: payment.GetPaymentStatusResponse.payment:type_name -> payment.Payment
	3,  // 16: payment.GetPaymentMethodsResponse.payment_methods:type_name -> payment.PaymentMethod
	1,  // 17: payment.AddPaymentMethodRequest.type:type_name -> payment.PaymentMethodType
	3,  // 18: payment.AddPaymentMethodResponse.payment_method:type_name -> payment.PaymentMethod
	4,  // 19: payment.PaymentService.CreatePaymentIntent:input_type -> payment.CreatePaymentIntentRequest
	6,  // 20: payment.PaymentService.ConfirmPayment:input_type -> payment.ConfirmPaymentRequest
	8,  // 21: payment.PaymentService.CancelPayment:input_type -> payment.CancelPaymentRequest
	10, // 22: payment.PaymentService.RefundPayment:input_type -> payment.RefundPaymentRequest
	12, // 23: payment.PaymentService.GetPaymentStatus:input_type -> payment.GetPaymentStatusRequest
	14, // 24: payment.PaymentService.GetPaymentMethods:input_type -> payment.GetPaymentMethodsRequest
	16, // 25: payment.PaymentService.AddPaymentMethod:input_type -> payment.AddPaymentMethodRequest
	18, // 26: payment.PaymentService.RemovePaymentMethod:input_type -> payment.RemovePaymentMethodRequest
	5,  // 27: payment.PaymentService.CreatePaymentIntent:output_type -> payment.CreatePaymentIntentResponse
	7,  // 28: payment.PaymentService.ConfirmPayment:output_type -> payment.ConfirmPaymentResponse
	9,  // 29: payment.PaymentService.CancelPayment:output_type -> payment.CancelPaymentResponse
	11, // 30: payment.PaymentService.RefundPayment:output_type -> payment.RefundPaymentResponse
	13, // 31: payment.PaymentService.GetPaymentStatus:output_type -> payment.GetPaymentStatusResponse
	15, // 32: payment.PaymentService.GetPaymentMethods:output_type -> payment.GetPaymentMethodsResponse
	17, // 33: payment.PaymentService.AddPaymentMethod:output_type -> payment.AddPaymentMethodResponse
	19, // 34: payment.PaymentService.RemovePaymentMethod:output_type -> payment.RemovePaymentMethodResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
