// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: product.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product status
type ProductStatus int32

const (
	ProductStatus_DRAFT        ProductStatus = 0
	ProductStatus_ACTIVE       ProductStatus = 1
	ProductStatus_INACTIVE     ProductStatus = 2
	ProductStatus_OUT_OF_STOCK ProductStatus = 3
	ProductStatus_DISCONTINUED ProductStatus = 4
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "DRAFT",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "OUT_OF_STOCK",
		4: "DISCONTINUED",
	}
	ProductStatus_value = map[string]int32{
		"DRAFT":        0,
		"ACTIVE":       1,
		"INACTIVE":     2,
		"OUT_OF_STOCK": 3,
		"DISCONTINUED": 4,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_product_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_product_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

// Product message
type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug            string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LongDescription string                 `protobuf:"bytes,5,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	Price           *Money                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice   *Money                 `protobuf:"bytes,7,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	CategoryId      string                 `protobuf:"bytes,8,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName    string                 `protobuf:"bytes,9,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Images          []string               `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	Variants        []*ProductVariant      `protobuf:"bytes,11,rep,name=variants,proto3" json:"variants,omitempty"`
	Specifications  map[string]string      `protobuf:"bytes,12,rep,name=specifications,proto3" json:"specifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags            []string               `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	Rating          float64                `protobuf:"fixed64,14,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewCount     int32                  `protobuf:"varint,15,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	IsFeatured      bool                   `protobuf:"varint,16,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	IsNew           bool                   `protobuf:"varint,17,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsOnSale        bool                   `protobuf:"varint,18,opt,name=is_on_sale,json=isOnSale,proto3" json:"is_on_sale,omitempty"`
	Sku             string                 `protobuf:"bytes,19,opt,name=sku,proto3" json:"sku,omitempty"`
	Status          ProductStatus          `protobuf:"varint,20,opt,name=status,proto3,enum=product.ProductStatus" json:"status,omitempty"`
	CreatedAt       *Timestamp             `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *Timestamp             `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *Product) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Product) GetOriginalPrice() *Money {
	if x != nil {
		return x.OriginalPrice
	}
	return nil
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Product) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Product) GetSpecifications() map[string]string {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *Product) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Product) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Product) GetIsOnSale() bool {
	if x != nil {
		return x.IsOnSale
	}
	return false
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_DRAFT
}

func (x *Product) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Product variant (size, color, etc.)
type ProductVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         *Money                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., {"size": "L", "color": "red"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductVariant) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductVariant) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductVariant) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ProductVariant) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductVariant) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Category
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	ProductCount  int32                  `protobuf:"varint,7,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *Timestamp             `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Category) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Category) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *Category) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Category) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Category) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Get product request
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Get product by slug request
type GetProductBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductBySlugRequest) Reset() {
	*x = GetProductBySlugRequest{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductBySlugRequest) ProtoMessage() {}

func (x *GetProductBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetProductBySlugRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetProductBySlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductBySlugResponse) Reset() {
	*x = GetProductBySlugResponse{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductBySlugResponse) ProtoMessage() {}

func (x *GetProductBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductBySlugResponse.ProtoReflect.Descriptor instead.
func (*GetProductBySlugResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductBySlugResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// List products request
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filters       *ProductFilters        `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	Sort          *ProductSort           `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProductsRequest) GetFilters() *ProductFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListProductsRequest) GetSort() *ProductSort {
	if x != nil {
		return x.Sort
	}
	return nil
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Product filters
type ProductFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MinPriceCents int64                  `protobuf:"varint,2,opt,name=min_price_cents,json=minPriceCents,proto3" json:"min_price_cents,omitempty"`
	MaxPriceCents int64                  `protobuf:"varint,3,opt,name=max_price_cents,json=maxPriceCents,proto3" json:"max_price_cents,omitempty"`
	MinRating     float64                `protobuf:"fixed64,4,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	InStockOnly   bool                   `protobuf:"varint,6,opt,name=in_stock_only,json=inStockOnly,proto3" json:"in_stock_only,omitempty"`
	FeaturedOnly  bool                   `protobuf:"varint,7,opt,name=featured_only,json=featuredOnly,proto3" json:"featured_only,omitempty"`
	OnSaleOnly    bool                   `protobuf:"varint,8,opt,name=on_sale_only,json=onSaleOnly,proto3" json:"on_sale_only,omitempty"`
	Status        ProductStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=product.ProductStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductFilters) Reset() {
	*x = ProductFilters{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFilters) ProtoMessage() {}

func (x *ProductFilters) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFilters.ProtoReflect.Descriptor instead.
func (*ProductFilters) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *ProductFilters) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductFilters) GetMinPriceCents() int64 {
	if x != nil {
		return x.MinPriceCents
	}
	return 0
}

func (x *ProductFilters) GetMaxPriceCents() int64 {
	if x != nil {
		return x.MaxPriceCents
	}
	return 0
}

func (x *ProductFilters) GetMinRating() float64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *ProductFilters) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductFilters) GetInStockOnly() bool {
	if x != nil {
		return x.InStockOnly
	}
	return false
}

func (x *ProductFilters) GetFeaturedOnly() bool {
	if x != nil {
		return x.FeaturedOnly
	}
	return false
}

func (x *ProductFilters) GetOnSaleOnly() bool {
	if x != nil {
		return x.OnSaleOnly
	}
	return false
}

func (x *ProductFilters) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_DRAFT
}

// Product sort
type ProductSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // price, rating, name, created_at
	Direction     SortDirection          `protobuf:"varint,2,opt,name=direction,proto3,enum=common.SortDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSort) Reset() {
	*x = ProductSort{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSort) ProtoMessage() {}

func (x *ProductSort) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSort.ProtoReflect.Descriptor instead.
func (*ProductSort) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *ProductSort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ProductSort) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_ASC
}

// Search products
type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filters       *ProductFilters        `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchProductsRequest) GetFilters() *ProductFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Suggestions   []string               `protobuf:"bytes,3,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *SearchProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *SearchProductsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchProductsResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

// List categories
type ListCategoriesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ParentId            string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // Empty for root categories
	IncludeProductCount bool                   `protobuf:"varint,2,opt,name=include_product_count,json=includeProductCount,proto3" json:"include_product_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *ListCategoriesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListCategoriesRequest) GetIncludeProductCount() bool {
	if x != nil {
		return x.IncludeProductCount
	}
	return false
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// Get category
type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *GetCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResponse) Reset() {
	*x = GetCategoryResponse{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResponse) ProtoMessage() {}

func (x *GetCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

func (x *GetCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

// Get related products
type GetRelatedProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedProductsRequest) Reset() {
	*x = GetRelatedProductsRequest{}
	mi := &file_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedProductsRequest) ProtoMessage() {}

func (x *GetRelatedProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedProductsRequest.ProtoReflect.Descriptor instead.
func (*GetRelatedProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{17}
}

func (x *GetRelatedProductsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetRelatedProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRelatedProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedProductsResponse) Reset() {
	*x = GetRelatedProductsResponse{}
	mi := &file_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedProductsResponse) ProtoMessage() {}

func (x *GetRelatedProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedProductsResponse.ProtoReflect.Descriptor instead.
func (*GetRelatedProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{18}
}

func (x *GetRelatedProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// Get price range
type GetPriceRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // Optional: filter by category
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRangeRequest) Reset() {
	*x = GetPriceRangeRequest{}
	mi := &file_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRangeRequest) ProtoMessage() {}

func (x *GetPriceRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRangeRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRangeRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{19}
}

func (x *GetPriceRangeRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type GetPriceRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPriceCents int64                  `protobuf:"varint,1,opt,name=min_price_cents,json=minPriceCents,proto3" json:"min_price_cents,omitempty"`
	MaxPriceCents int64                  `protobuf:"varint,2,opt,name=max_price_cents,json=maxPriceCents,proto3" json:"max_price_cents,omitempty"`
	AvgPriceCents float64                `protobuf:"fixed64,3,opt,name=avg_price_cents,json=avgPriceCents,proto3" json:"avg_price_cents,omitempty"`
	ProductCount  int32                  `protobuf:"varint,4,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRangeResponse) Reset() {
	*x = GetPriceRangeResponse{}
	mi := &file_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRangeResponse) ProtoMessage() {}

func (x *GetPriceRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRangeResponse.ProtoReflect.Descriptor instead.
func (*GetPriceRangeResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{20}
}

func (x *GetPriceRangeResponse) GetMinPriceCents() int64 {
	if x != nil {
		return x.MinPriceCents
	}
	return 0
}

func (x *GetPriceRangeResponse) GetMaxPriceCents() int64 {
	if x != nil {
		return x.MaxPriceCents
	}
	return 0
}

func (x *GetPriceRangeResponse) GetAvgPriceCents() float64 {
	if x != nil {
		return x.AvgPriceCents
	}
	return 0
}

func (x *GetPriceRangeResponse) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

// Create product (Admin)
type CreateProductRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug            string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LongDescription string                 `protobuf:"bytes,4,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	Price           *Money                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice   *Money                 `protobuf:"bytes,6,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	CategoryId      string                 `protobuf:"bytes,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Images          []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	Specifications  map[string]string      `protobuf:"bytes,9,rep,name=specifications,proto3" json:"specifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags            []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Sku             string                 `protobuf:"bytes,11,opt,name=sku,proto3" json:"sku,omitempty"`
	IsFeatured      bool                   `protobuf:"varint,12,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{21}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreateProductRequest) GetOriginalPrice() *Money {
	if x != nil {
		return x.OriginalPrice
	}
	return nil
}

func (x *CreateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateProductRequest) GetSpecifications() map[string]string {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *CreateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{22}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Update product (Admin)
type UpdateProductRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	LongDescription *string                `protobuf:"bytes,4,opt,name=long_description,json=longDescription,proto3,oneof" json:"long_description,omitempty"`
	Price           *Money                 `protobuf:"bytes,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	CategoryId      *string                `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Images          []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Status          *ProductStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=product.ProductStatus,oneof" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetLongDescription() string {
	if x != nil && x.LongDescription != nil {
		return *x.LongDescription
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *UpdateProductRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *UpdateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateProductRequest) GetStatus() ProductStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ProductStatus_DRAFT
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_product_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Delete product (Admin)
type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_product_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get products by IDs
type GetProductsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIdsRequest) Reset() {
	*x = GetProductsByIdsRequest{}
	mi := &file_product_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIdsRequest) ProtoMessage() {}

func (x *GetProductsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{27}
}

func (x *GetProductsByIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetProductsByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIdsResponse) Reset() {
	*x = GetProductsByIdsResponse{}
	mi := &file_product_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIdsResponse) ProtoMessage() {}

func (x *GetProductsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{28}
}

func (x *GetProductsByIdsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\x1a\fcommon.proto\"\xd8\x06\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12)\n" +
	"\x10long_description\x18\x05 \x01(\tR\x0flongDescription\x12#\n" +
	"\x05price\x18\x06 \x01(\v2\r.common.MoneyR\x05price\x124\n" +
	"\x0eoriginal_price\x18\a \x01(\v2\r.common.MoneyR\roriginalPrice\x12\x1f\n" +
	"\vcategory_id\x18\b \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\t \x01(\tR\fcategoryName\x12\x16\n" +
	"\x06images\x18\n" +
	" \x03(\tR\x06images\x123\n" +
	"\bvariants\x18\v \x03(\v2\x17.product.ProductVariantR\bvariants\x12L\n" +
	"\x0especifications\x18\f \x03(\v2$.product.Product.SpecificationsEntryR\x0especifications\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\x12\x16\n" +
	"\x06rating\x18\x0e \x01(\x01R\x06rating\x12!\n" +
	"\freview_count\x18\x0f \x01(\x05R\vreviewCount\x12\x1f\n" +
	"\vis_featured\x18\x10 \x01(\bR\n" +
	"isFeatured\x12\x15\n" +
	"\x06is_new\x18\x11 \x01(\bR\x05isNew\x12\x1c\n" +
	"\n" +
	"is_on_sale\x18\x12 \x01(\bR\bisOnSale\x12\x10\n" +
	"\x03sku\x18\x13 \x01(\tR\x03sku\x12.\n" +
	"\x06status\x18\x14 \x01(\x0e2\x16.product.ProductStatusR\x06status\x120\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x11.common.TimestampR\tupdatedAt\x1aA\n" +
	"\x13SpecificationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x02\n" +
	"\x0eProductVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12#\n" +
	"\x05price\x18\x05 \x01(\v2\r.common.MoneyR\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12G\n" +
	"\n" +
	"attributes\x18\a \x03(\v2'.product.ProductVariant.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12#\n" +
	"\rproduct_count\x18\a \x01(\x05R\fproductCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\x05R\tsortOrder\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x120\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x11.common.TimestampR\tupdatedAt\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"-\n" +
	"\x17GetProductBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"F\n" +
	"\x18GetProductBySlugResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"\xad\x01\n" +
	"\x13ListProductsRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x121\n" +
	"\afilters\x18\x02 \x01(\v2\x17.product.ProductFiltersR\afilters\x12(\n" +
	"\x04sort\x18\x03 \x01(\v2\x14.product.ProductSortR\x04sort\"\x80\x01\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"\xcf\x02\n" +
	"\x0eProductFilters\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12&\n" +
	"\x0fmin_price_cents\x18\x02 \x01(\x03R\rminPriceCents\x12&\n" +
	"\x0fmax_price_cents\x18\x03 \x01(\x03R\rmaxPriceCents\x12\x1d\n" +
	"\n" +
	"min_rating\x18\x04 \x01(\x01R\tminRating\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\"\n" +
	"\rin_stock_only\x18\x06 \x01(\bR\vinStockOnly\x12#\n" +
	"\rfeatured_only\x18\a \x01(\bR\ffeaturedOnly\x12 \n" +
	"\fon_sale_only\x18\b \x01(\bR\n" +
	"onSaleOnly\x12.\n" +
	"\x06status\x18\t \x01(\x0e2\x16.product.ProductStatusR\x06status\"X\n" +
	"\vProductSort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x123\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x15.common.SortDirectionR\tdirection\"\x9b\x01\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x121\n" +
	"\afilters\x18\x03 \x01(\v2\x17.product.ProductFiltersR\afilters\"\xa4\x01\n" +
	"\x16SearchProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\x12 \n" +
	"\vsuggestions\x18\x03 \x03(\tR\vsuggestions\"h\n" +
	"\x15ListCategoriesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x122\n" +
	"\x15include_product_count\x18\x02 \x01(\bR\x13includeProductCount\"K\n" +
	"\x16ListCategoriesResponse\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x11.product.CategoryR\n" +
	"categories\"$\n" +
	"\x12GetCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x13GetCategoryResponse\x12-\n" +
	"\bcategory\x18\x01 \x01(\v2\x11.product.CategoryR\bcategory\"P\n" +
	"\x19GetRelatedProductsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x1aGetRelatedProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\"7\n" +
	"\x14GetPriceRangeRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"\xb4\x01\n" +
	"\x15GetPriceRangeResponse\x12&\n" +
	"\x0fmin_price_cents\x18\x01 \x01(\x03R\rminPriceCents\x12&\n" +
	"\x0fmax_price_cents\x18\x02 \x01(\x03R\rmaxPriceCents\x12&\n" +
	"\x0favg_price_cents\x18\x03 \x01(\x01R\ravgPriceCents\x12#\n" +
	"\rproduct_count\x18\x04 \x01(\x05R\fproductCount\"\x84\x04\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10long_description\x18\x04 \x01(\tR\x0flongDescription\x12#\n" +
	"\x05price\x18\x05 \x01(\v2\r.common.MoneyR\x05price\x124\n" +
	"\x0eoriginal_price\x18\x06 \x01(\v2\r.common.MoneyR\roriginalPrice\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\tR\n" +
	"categoryId\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\x12Y\n" +
	"\x0especifications\x18\t \x03(\v21.product.CreateProductRequest.SpecificationsEntryR\x0especifications\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x10\n" +
	"\x03sku\x18\v \x01(\tR\x03sku\x12\x1f\n" +
	"\vis_featured\x18\f \x01(\bR\n" +
	"isFeatured\x1aA\n" +
	"\x13SpecificationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x15CreateProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"\x86\x03\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12.\n" +
	"\x10long_description\x18\x04 \x01(\tH\x02R\x0flongDescription\x88\x01\x01\x12(\n" +
	"\x05price\x18\x05 \x01(\v2\r.common.MoneyH\x03R\x05price\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x06 \x01(\tH\x04R\n" +
	"categoryId\x88\x01\x01\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x16.product.ProductStatusH\x05R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x13\n" +
	"\x11_long_descriptionB\b\n" +
	"\x06_priceB\x0e\n" +
	"\f_category_idB\t\n" +
	"\a_status\"C\n" +
	"\x15UpdateProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x17GetProductsByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"H\n" +
	"\x18GetProductsByIdsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts*X\n" +
	"\rProductStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\x10\n" +
	"\fOUT_OF_STOCK\x10\x03\x12\x10\n" +
	"\fDISCONTINUED\x10\x042\xe5\a\n" +
	"\x0eProductService\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x1b.product.GetProductResponse\x12W\n" +
	"\x10GetProductBySlug\x12 .product.GetProductBySlugRequest\x1a!.product.GetProductBySlugResponse\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12Q\n" +
	"\x0eSearchProducts\x12\x1e.product.SearchProductsRequest\x1a\x1f.product.SearchProductsResponse\x12Q\n" +
	"\x0eListCategories\x12\x1e.product.ListCategoriesRequest\x1a\x1f.product.ListCategoriesResponse\x12H\n" +
	"\vGetCategory\x12\x1b.product.GetCategoryRequest\x1a\x1c.product.GetCategoryResponse\x12]\n" +
	"\x12GetRelatedProducts\x12\".product.GetRelatedProductsRequest\x1a#.product.GetRelatedProductsResponse\x12N\n" +
	"\rGetPriceRange\x12\x1d.product.GetPriceRangeRequest\x1a\x1e.product.GetPriceRangeResponse\x12N\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x1e.product.CreateProductResponse\x12N\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x1e.product.UpdateProductResponse\x12N\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponse\x12W\n" +
	"\x10GetProductsByIds\x12 .product.GetProductsByIdsRequest\x1a!.product.GetProductsByIdsResponseB/Z-github.com/cqchien/ecomerce-rec/backend/protob\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_product_proto_goTypes = []any{
	(ProductStatus)(0),                 // 0: product.ProductStatus
	(*Product)(nil),                    // 1: product.Product
	(*ProductVariant)(nil),             // 2: product.ProductVariant
	(*Category)(nil),                   // 3: product.Category
	(*GetProductRequest)(nil),          // 4: product.GetProductRequest
	(*GetProductResponse)(nil),         // 5: product.GetProductResponse
	(*GetProductBySlugRequest)(nil),    // 6: product.GetProductBySlugRequest
	(*GetProductBySlugResponse)(nil),   // 7: product.GetProductBySlugResponse
	(*ListProductsRequest)(nil),        // 8: product.ListProductsRequest
	(*ListProductsResponse)(nil),       // 9: product.ListProductsResponse
	(*ProductFilters)(nil),             // 10: product.ProductFilters
	(*ProductSort)(nil),                // 11: product.ProductSort
	(*SearchProductsRequest)(nil),      // 12: product.SearchProductsRequest
	(*SearchProductsResponse)(nil),     // 13: product.SearchProductsResponse
	(*ListCategoriesRequest)(nil),      // 14: product.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),     // 15: product.ListCategoriesResponse
	(*GetCategoryRequest)(nil),         // 16: product.GetCategoryRequest
	(*GetCategoryResponse)(nil),        // 17: product.GetCategoryResponse
	(*GetRelatedProductsRequest)(nil),  // 18: product.GetRelatedProductsRequest
	(*GetRelatedProductsResponse)(nil), // 19: product.GetRelatedProductsResponse
	(*GetPriceRangeRequest)(nil),       // 20: product.GetPriceRangeRequest
	(*GetPriceRangeResponse)(nil),      // 21: product.GetPriceRangeResponse
	(*CreateProductRequest)(nil),       // 22: product.CreateProductRequest
	(*CreateProductResponse)(nil),      // 23: product.CreateProductResponse
	(*UpdateProductRequest)(nil),       // 24: product.UpdateProductRequest
	(*UpdateProductResponse)(nil),      // 25: product.UpdateProductResponse
	(*DeleteProductRequest)(nil),       // 26: product.DeleteProductRequest
	(*DeleteProductResponse)(nil),      // 27: product.DeleteProductResponse
	(*GetProductsByIdsRequest)(nil),    // 28: product.GetProductsByIdsRequest
	(*GetProductsByIdsResponse)(nil),   // 29: product.GetProductsByIdsResponse
	nil,                                // 30: product.Product.SpecificationsEntry
	nil,                                // 31: product.ProductVariant.AttributesEntry
	nil,                                // 32: product.CreateProductRequest.SpecificationsEntry
	(*Money)(nil),                      // 33: common.Money
	(*Timestamp)(nil),                  // 34: common.Timestamp
	(*PaginationRequest)(nil),          // 35: common.PaginationRequest
	(*PaginationResponse)(nil),         // 36: common.PaginationResponse
	(SortDirection)(0),                 // 37: common.SortDirection
}
var file_product_proto_depIdxs = []int32{
	33, // 0: product.Product.price:type_name -> common.Money
	33, // 1: product.Product.original_price:type_name -> common.Money
	2,  // 2: product.Product.variants:type_name -> product.ProductVariant
	30, // 3: product.Product.specifications:type_name -> product.Product.SpecificationsEntry
	0,  // 4: product.Product.status:type_name -> product.ProductStatus
	34, // 5: product.Product.created_at:type_name -> common.Timestamp
	34, // 6: product.Product.updated_at:type_name -> common.Timestamp
	33, // 7: product.ProductVariant.price:type_name -> common.Money
	31, // 8: product.ProductVariant.attributes:type_name -> product.ProductVariant.AttributesEntry
	34, // 9: product.Category.created_at:type_name -> common.Timestamp
	34, // 10: product.Category.updated_at:type_name -> common.Timestamp
	1,  // 11: product.GetProductResponse.product:type_name -> product.Product
	1,  // 12: product.GetProductBySlugResponse.product:type_name -> product.Product
	35, // 13: product.ListProductsRequest.pagination:type_name -> common.PaginationRequest
	10, // 14: product.ListProductsRequest.filters:type_name -> product.ProductFilters
	11, // 15: product.ListProductsRequest.sort:type_name -> product.ProductSort
	1,  // 16: product.ListProductsResponse.products:type_name -> product.Product
	36, // 17: product.ListProductsResponse.pagination:type_name -> common.PaginationResponse
	0,  // 18: product.ProductFilters.status:type_name -> product.ProductStatus
	37, // 19: product.ProductSort.direction:type_name -> common.SortDirection
	35, // 20: product.SearchProductsRequest.pagination:type_name -> common.PaginationRequest
	10, // 21: product.SearchProductsRequest.filters:type_name -> product.ProductFilters
	1,  // 22: product.SearchProductsResponse.products:type_name -> product.Product
	36, // 23: product.SearchProductsResponse.pagination:type_name -> common.PaginationResponse
	3,  // 24: product.ListCategoriesResponse.categories:type_name -> product.Category
	3,  // 25: product.GetCategoryResponse.category:type_name -> product.Category
	1,  // 26: product.GetRelatedProductsResponse.products:type_name -> product.Product
	33, // 27: product.CreateProductRequest.price:type_name -> common.Money
	33, // 28: product.CreateProductRequest.original_price:type_name -> common.Money
	32, // 29: product.CreateProductRequest.specifications:type_name -> product.CreateProductRequest.SpecificationsEntry
	1,  // 30: product.CreateProductResponse.product:type_name -> product.Product
	33, // 31: product.UpdateProductRequest.price:type_name -> common.Money
	0,  // 32: product.UpdateProductRequest.status:type_name -> product.ProductStatus
	1,  // 33: product.UpdateProductResponse.product:type_name -> product.Product
	1,  // 34: product.GetProductsByIdsResponse.products:type_name -> product.Product
	4,  // 35: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	6,  // 36: product.ProductService.GetProductBySlug:input_type -> product.GetProductBySlugRequest
	8,  // 37: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	12, // 38: product.ProductService.SearchProducts:input_type -> product.SearchProductsRequest
	14, // 39: product.ProductService.ListCategories:input_type -> product.ListCategoriesRequest
	16, // 40: product.ProductService.GetCategory:input_type -> product.GetCategoryRequest
	18, // 41: product.ProductService.GetRelatedProducts:input_type -> product.GetRelatedProductsRequest
	20, // 42: product.ProductService.GetPriceRange:input_type -> product.GetPriceRangeRequest
	22, // 43: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	24, // 44: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	26, // 45: product.ProductService.DeleteProduct:input_type -> product.DeleteProductRequest
	28, // 46: product.ProductService.GetProductsByIds:input_type -> product.GetProductsByIdsRequest
	5,  // 47: product.ProductService.GetProduct:output_type -> product.GetProductResponse
	7,  // 48: product.ProductService.GetProductBySlug:output_type -> product.GetProductBySlugResponse
	9,  // 49: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	13, // 50: product.ProductService.SearchProducts:output_type -> product.SearchProductsResponse
	15, // 51: product.ProductService.ListCategories:output_type -> product.ListCategoriesResponse
	17, // 52: product.ProductService.GetCategory:output_type -> product.GetCategoryResponse
	19, // 53: product.ProductService.GetRelatedProducts:output_type -> product.GetRelatedProductsResponse
	21, // 54: product.ProductService.GetPriceRange:output_type -> product.GetPriceRangeResponse
	23, // 55: product.ProductService.CreateProduct:output_type -> product.CreateProductResponse
	25, // 56: product.ProductService.UpdateProduct:output_type -> product.UpdateProductResponse
	27, // 57: product.ProductService.DeleteProduct:output_type -> product.DeleteProductResponse
	29, // 58: product.ProductService.GetProductsByIds:output_type -> product.GetProductsByIdsResponse
	47, // [47:59] is the sub-list for method output_type
	35, // [35:47] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	file_common_proto_init()
	file_product_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		EnumInfos:         file_product_proto_enumTypes,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
