// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: recommendation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommendationService_RecordInteraction_FullMethodName         = "/recommendation.RecommendationService/RecordInteraction"
	RecommendationService_GetUserRecommendations_FullMethodName    = "/recommendation.RecommendationService/GetUserRecommendations"
	RecommendationService_GetProductRecommendations_FullMethodName = "/recommendation.RecommendationService/GetProductRecommendations"
	RecommendationService_GetTrendingProducts_FullMethodName       = "/recommendation.RecommendationService/GetTrendingProducts"
	RecommendationService_CalculateSimilarities_FullMethodName     = "/recommendation.RecommendationService/CalculateSimilarities"
	RecommendationService_CalculateTrendingScores_FullMethodName   = "/recommendation.RecommendationService/CalculateTrendingScores"
	RecommendationService_HealthCheck_FullMethodName               = "/recommendation.RecommendationService/HealthCheck"
)

// RecommendationServiceClient is the client API for RecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendationServiceClient interface {
	// Record user interaction with a product
	RecordInteraction(ctx context.Context, in *RecordInteractionRequest, opts ...grpc.CallOption) (*RecordInteractionResponse, error)
	// Get personalized recommendations for a user
	GetUserRecommendations(ctx context.Context, in *GetUserRecommendationsRequest, opts ...grpc.CallOption) (*GetUserRecommendationsResponse, error)
	// Get products similar to a given product
	GetProductRecommendations(ctx context.Context, in *GetProductRecommendationsRequest, opts ...grpc.CallOption) (*GetProductRecommendationsResponse, error)
	// Get trending products
	GetTrendingProducts(ctx context.Context, in *GetTrendingProductsRequest, opts ...grpc.CallOption) (*GetTrendingProductsResponse, error)
	// Calculate product similarities (admin operation)
	CalculateSimilarities(ctx context.Context, in *CalculateSimilaritiesRequest, opts ...grpc.CallOption) (*CalculateSimilaritiesResponse, error)
	// Calculate trending scores (admin operation)
	CalculateTrendingScores(ctx context.Context, in *CalculateTrendingScoresRequest, opts ...grpc.CallOption) (*CalculateTrendingScoresResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type recommendationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationServiceClient(cc grpc.ClientConnInterface) RecommendationServiceClient {
	return &recommendationServiceClient{cc}
}

func (c *recommendationServiceClient) RecordInteraction(ctx context.Context, in *RecordInteractionRequest, opts ...grpc.CallOption) (*RecordInteractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordInteractionResponse)
	err := c.cc.Invoke(ctx, RecommendationService_RecordInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetUserRecommendations(ctx context.Context, in *GetUserRecommendationsRequest, opts ...grpc.CallOption) (*GetUserRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetUserRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetProductRecommendations(ctx context.Context, in *GetProductRecommendationsRequest, opts ...grpc.CallOption) (*GetProductRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetProductRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetTrendingProducts(ctx context.Context, in *GetTrendingProductsRequest, opts ...grpc.CallOption) (*GetTrendingProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendingProductsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetTrendingProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) CalculateSimilarities(ctx context.Context, in *CalculateSimilaritiesRequest, opts ...grpc.CallOption) (*CalculateSimilaritiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateSimilaritiesResponse)
	err := c.cc.Invoke(ctx, RecommendationService_CalculateSimilarities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) CalculateTrendingScores(ctx context.Context, in *CalculateTrendingScoresRequest, opts ...grpc.CallOption) (*CalculateTrendingScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateTrendingScoresResponse)
	err := c.cc.Invoke(ctx, RecommendationService_CalculateTrendingScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, RecommendationService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServiceServer is the server API for RecommendationService service.
// All implementations must embed UnimplementedRecommendationServiceServer
// for forward compatibility.
type RecommendationServiceServer interface {
	// Record user interaction with a product
	RecordInteraction(context.Context, *RecordInteractionRequest) (*RecordInteractionResponse, error)
	// Get personalized recommendations for a user
	GetUserRecommendations(context.Context, *GetUserRecommendationsRequest) (*GetUserRecommendationsResponse, error)
	// Get products similar to a given product
	GetProductRecommendations(context.Context, *GetProductRecommendationsRequest) (*GetProductRecommendationsResponse, error)
	// Get trending products
	GetTrendingProducts(context.Context, *GetTrendingProductsRequest) (*GetTrendingProductsResponse, error)
	// Calculate product similarities (admin operation)
	CalculateSimilarities(context.Context, *CalculateSimilaritiesRequest) (*CalculateSimilaritiesResponse, error)
	// Calculate trending scores (admin operation)
	CalculateTrendingScores(context.Context, *CalculateTrendingScoresRequest) (*CalculateTrendingScoresResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedRecommendationServiceServer()
}

// UnimplementedRecommendationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationServiceServer struct{}

func (UnimplementedRecommendationServiceServer) RecordInteraction(context.Context, *RecordInteractionRequest) (*RecordInteractionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordInteraction not implemented")
}
func (UnimplementedRecommendationServiceServer) GetUserRecommendations(context.Context, *GetUserRecommendationsRequest) (*GetUserRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) GetProductRecommendations(context.Context, *GetProductRecommendationsRequest) (*GetProductRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) GetTrendingProducts(context.Context, *GetTrendingProductsRequest) (*GetTrendingProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingProducts not implemented")
}
func (UnimplementedRecommendationServiceServer) CalculateSimilarities(context.Context, *CalculateSimilaritiesRequest) (*CalculateSimilaritiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateSimilarities not implemented")
}
func (UnimplementedRecommendationServiceServer) CalculateTrendingScores(context.Context, *CalculateTrendingScoresRequest) (*CalculateTrendingScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateTrendingScores not implemented")
}
func (UnimplementedRecommendationServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRecommendationServiceServer) mustEmbedUnimplementedRecommendationServiceServer() {}
func (UnimplementedRecommendationServiceServer) testEmbeddedByValue()                               {}

// UnsafeRecommendationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationServiceServer will
// result in compilation errors.
type UnsafeRecommendationServiceServer interface {
	mustEmbedUnimplementedRecommendationServiceServer()
}

func RegisterRecommendationServiceServer(s grpc.ServiceRegistrar, srv RecommendationServiceServer) {
	// If the following call panics, it indicates UnimplementedRecommendationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendationService_ServiceDesc, srv)
}

func _RecommendationService_RecordInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).RecordInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_RecordInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).RecordInteraction(ctx, req.(*RecordInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetUserRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetUserRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetUserRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetUserRecommendations(ctx, req.(*GetUserRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetProductRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetProductRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetProductRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetProductRecommendations(ctx, req.(*GetProductRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetTrendingProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetTrendingProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetTrendingProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetTrendingProducts(ctx, req.(*GetTrendingProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_CalculateSimilarities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateSimilaritiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).CalculateSimilarities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_CalculateSimilarities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).CalculateSimilarities(ctx, req.(*CalculateSimilaritiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_CalculateTrendingScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateTrendingScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).CalculateTrendingScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_CalculateTrendingScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).CalculateTrendingScores(ctx, req.(*CalculateTrendingScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationService_ServiceDesc is the grpc.ServiceDesc for RecommendationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommendation.RecommendationService",
	HandlerType: (*RecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordInteraction",
			Handler:    _RecommendationService_RecordInteraction_Handler,
		},
		{
			MethodName: "GetUserRecommendations",
			Handler:    _RecommendationService_GetUserRecommendations_Handler,
		},
		{
			MethodName: "GetProductRecommendations",
			Handler:    _RecommendationService_GetProductRecommendations_Handler,
		},
		{
			MethodName: "GetTrendingProducts",
			Handler:    _RecommendationService_GetTrendingProducts_Handler,
		},
		{
			MethodName: "CalculateSimilarities",
			Handler:    _RecommendationService_CalculateSimilarities_Handler,
		},
		{
			MethodName: "CalculateTrendingScores",
			Handler:    _RecommendationService_CalculateTrendingScores_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RecommendationService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommendation.proto",
}
